#! /bin/bash
nArg=false # user doesn't enter -n
if [ -n "$1" ]
then
    if [ $1 == "-n" ]
    then
        # user enter -n
        nArg=true
        shift
    fi
    if [ $1 == "+" ]
    then
        #addition
        shift
        cptaddition=0
        for numbers in $*
        do
            cptaddition=`echo "$numbers+$cptaddition" | bc`
        done
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptaddition
            echo
        else
            echo $cptaddition
        fi
    elif [ $1 == "-" ]
    then
        #substraction
        shift
        cptsubstract=$1
        shift
        for numbers in $*
        do
            cptsubstract=`echo "$cptsubstract-$numbers" | bc`
        done
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptsubstract
            echo
        else
            echo $cptsubstract
        fi
    elif [ $1 == "x" ]
    then
        #Multiplication
        shift
        cptmulti=$1
        shift
        for numbers in $*
        do
            cptmulti=`echo "$cptmulti*$numbers" | bc`
        done
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptmulti
            echo
        else
            echo $cptmulti
        fi

    elif [ $1 == "/" ]
    then
        #division
        shift
        cptdivi=$1
        shift
        for numbers in $*
        do
            cptdivi=`echo "scale=5;$cptdivi/$numbers" | bc -l`
        done
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptdivi
            echo
        else
            echo $cptdivi
        fi
    elif [ $1 == "%" ]
    then
        #modulo
        shift
        let cptmod=($1%$2)
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptmod
            echo
        else
            echo $cptmod
        fi
    elif [ $1 == "ex" ]
    then
        #exponnent
        shift
        let cptexp=($1**$2)
        if [ $nArg == false ]
        then
            echo
            echo The answer is $cptexp
            echo
        else
            echo $cptexp
        fi
    elif [ $1 == "sqr" ]
    then
        #squareroot
        shift
        squareroot=`echo "sqrt($1)" | bc -l`
        if [ $nArg == false ]
        then
            echo
            echo The answer is $squareroot
            echo
        else
            echo $squareroot
        fi
    elif [ $1 == "help" ] || [ $1 == "man" ]
    then
        #help
            echo
            echo "For instructions visit https://obrassard.github.io/bashcalculator"
            echo
    else
        #not a valid operator
        echo
        echo "Error in command"
        echo "Invalids Arguments"
        echo "calcul.sh [-n] [+, -, x, /, ex, %, sqrt] [numbers]"
        echo
        echo "Try: calcul.sh + 2 3 4"
        echo
    fi
else
    #no Arguments
    echo
    echo "Error in command"
    echo "Invalids Arguments"
    echo "calcul.sh [-n] [+, -, x, /, ex, %, sqrt] [numbers]"
    echo
    echo "Try: calcul.sh + 2 3 4"
    echo
fi
