#! /bin/bash
nArg=false # user doesn't enter -n
if [ -n "$1" ]
then
    if [ $1 == "-n" ]
    then
        # user enter -n
        nArg=true
        shift
    fi
    if [ $1 == "+" ]
    then
        #addition
        shift
        let cptaddition=0
        for nombres in $*
        do
            let cptaddition+=$nombres
        done
        if [ $nArg == false ]
        then
            echo
            echo La réponse est $cptaddition
            echo
        else
            echo $cptaddition
        fi
    elif [ $1 == "-" ]
    then
        #substraction
        shift
        let cptsubstract=$1
        shift
        for nombres in $*
        do
            let cptsubstract-=$nombres
        done
        if [ $nArg == false ]
        then
            echo
            echo La réponse est $cptsubstract
            echo
        else
            echo $cptsubstract
        fi
    elif [ $1 == "x" ]
    then
        #Multiplication
        shift
        let cptmulti=$1
        shift
        for nombres in $*
        do
            let cptmulti=$cptmulti*$nombres
        done
        if [ $nArg == false ]
        then
            echo
            echo La réponse est $cptmulti
            echo
        else
            echo $cptmulti
        fi

    elif [ $1 == "/" ]
    then
        #division
        shift
        let cptdivi=$1
        shift
        for nombres in $*
        do
            let cptdivi=$cptdivi/$nombres
        done
        if [ $nArg == false ]
        then
            echo
            echo La réponse est $cptdivi
            echo
        else
            echo $cptdivi
        fi
    elif [ $1 == "help" ] || [ $1 == "man" ]
    then
        #help
            echo
            echo "Pour voir les instructions visitez https://github.com/obrassard/bash_calculator/"
            echo
    else
        #not a valid operator
        echo
        echo "Erreur dans l'appel du script"
        echo "Arguments invalides"
        echo "calcul.sh [-n] [+,-,x,/] [nombres]"
        echo
        echo "Essayez: calcul.sh + 2 3 4"
        echo
    fi
else
    #no Arguments
    echo
    echo "Erreur dans l'appel du script"
    echo "Arguments invalides"
    echo "calcul.sh [-n] [+,-,x,/] [nombres]"
    echo
    echo "Essayez: calcul.sh + 2 3 4"
    echo
fi
